trial2 of trying to get error file

diff --git a/.github/workflows/doxygen_errors.yml b/.github/workflows/doxygen_errors.yml
--- a/.github/workflows/doxygen_errors.yml
+++ b/.github/workflows/doxygen_errors.yml
@@ -27,14 +27,15 @@ jobs:
         id: doxygen
         run: |
           mkdir -p build/gh_pages
-          doxygen || echo "Doxygen failed with an exit code of $?"
+          doxygen || echo "doxygen failed with an exit code of $?"
           doxygen 2> doxygen_errors.txt
 
-      - name: Errors in the Doxygen Documentation
+      - name: Show Doxygen errors
         if: failure()
         run: |
-          echo "errors, File displayed:"
+          echo "Errors in the Doxygen Documentation:"
           cat doxygen_errors.txt
+
       
           
 
